repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace  # убирает лишние пробелы
      - id: check-added-large-files  # проверяет тяжелые файлы на изменения
      - id: check-yaml  # проверяет синтаксис .yaml файлов
      - id: check-json  # проверяет синтаксис .json файлов
        exclude: launch.json
      - id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
      - id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.
      - id: double-quote-string-fixer  # заменяет " на '
      - id: end-of-file-fixer  # добавляет пустую строку в конце файла

  # Отсортировывает импорты в проекте
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files ]

  # Обновляет синтаксис Python кода в соответствии с последними версиями
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [ --py310-plus ]

  # Форматирует код под PEP8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: [ --max-line-length=120, --in-place ]

  # Сканер стилистических ошибок, нарушающие договоренности PEP8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        exclude: "__init__.py|alembic"
        args: [ "--ignore=E501,F821", "--max-line-length=120" ]

  # Проверка статических типов с помощью mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        exclude: '^(alembic/|some_other_dir/)'  # Используйте регулярные выражения для исключения
        args:
          - "--install-types"
          - "--non-interactive"
          - "--ignore-missing-imports"
