version: '3.8'
name: faststream-template-tests
services:
  tests:
    build: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "postgres_test"
      POSTGRES_DB: "test"
      RABBIT_HOST: "rabbit_test"
      REDIS_HOST: "redis_test"
      REDIS_DB: "1"
    ports:
      - "8000:8000"
    entrypoint: sh -c "poetry run pytest"
    depends_on:
      postgres_test:
        condition: service_healthy
      rabbit_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy

  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: "test"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

  rabbit_test:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: $RABBIT_USERNAME
      RABBITMQ_DEFAULT_PASS: $RABBIT_PASSWORD
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmqctl ping
      interval: 10s
      timeout: 5s
      retries: 3

  redis_test:
    image: redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 30s
      retries: 5
