[project]
name = "faststream-template"
version = "0.1.0"
description = ""
authors = [
    {name = "aSel1x",email = "asel1x@icloud.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "litestar (>=2,<3)",
    "sqlalchemy (>=2,<3)",
    "alembic (>=1.15.2,<2.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "greenlet (>=3.2.1,<4.0.0)",
    "bcrypt (>=4.3.0,<5.0.0)",
    "uvicorn (>=0.34.2,<0.35.0)",
    "dishka (>=1.5.3,<2.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
