[project]
name = "faststream-template"
version = "0.1.0"
description = ""
authors = [
    {name = "aSel1x",email = "asel1x@icloud.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.0",
    "asyncpg>=0.30.0",
    "bcrypt>=5.0.0",
    "faststream[cli,rabbit]>=0.6.2",
    "greenlet>=3.2.4",
    "litestar>=2.18.0",
    "pyjwt>=2.10.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "python-dotenv>=1.1.1",
    "spritze==0.3.5",
    "sqlalchemy>=2.0.44",
    "types-pyjwt>=1.7.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.32.1",
    "ruff>=0.14.2",
]

[tool.basedpyright]
ignore = [
    "**/migrations",
]
