from datetime import datetime
from typing import Protocol


class RateLimiterInterface(Protocol):
    async def check(self, key: str) -> tuple[bool, int, datetime | None]: ...

    async def reset(self, key: str) -> None: ...


class LoginAttemptLimiterInterface(Protocol):
    async def record_failed_login(self, ip: str) -> bool: ...

    async def is_locked(self, ip: str) -> bool: ...

    async def get_remaining_lock_time(self, ip: str) -> int: ...

    async def reset(self, ip: str) -> None: ...
