from typing import Protocol


class TwoFactorInterface(Protocol):
    def generate_secret(self) -> str: ...

    def get_provisioning_uri(self, secret: str, username: str, issuer: str = 'BackendTemplate') -> str: ...

    def verify_code(self, secret: str, code: str) -> bool: ...
