"""empty message

Revision ID: d62ade67f6dc
Revises:
Create Date: 2024-07-11 18:52:19.986002

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

import app
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd62ade67f6dc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('created_at', app.types.unix.Unixepoch(), nullable=False),
                    sa.Column('updated_at', app.types.unix.Unixepoch(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
