from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from domain.user.value_objects import RoleID, RoleName, UserID

if TYPE_CHECKING:
    from domain.user.entities.rbac import Permission, Role, UserRole


class PermissionRepositoryInterface(Protocol):
    async def acquire_by_name(self, name: str) -> Permission | None: ...

    async def get_all(self) -> list[Permission]: ...

    async def add(self, permission: Permission) -> None: ...


class RoleRepositoryInterface(Protocol):
    async def acquire_by_id(self, role_id: RoleID) -> Role | None: ...

    async def acquire_by_name(self, name: RoleName) -> Role | None: ...

    async def get_all(self) -> list[Role]: ...

    async def add(self, role: Role) -> None: ...

    async def update(self, role: Role) -> None: ...

    async def delete(self, role_id: RoleID) -> None: ...


class UserRoleRepositoryInterface(Protocol):
    async def acquire_by_user_id(self, user_id: UserID) -> list[UserRole]: ...

    async def acquire_by_user_and_role(
        self, user_id: UserID, role_id: RoleID
    ) -> UserRole | None: ...

    async def add(self, user_role: UserRole) -> None: ...

    async def delete(self, user_id: UserID, role_id: RoleID) -> None: ...

    async def delete_by_user_id(self, user_id: UserID) -> None: ...
